
import type { Criterion, CertificationLevel } from './types';

export const criteria: Criterion[] = [
  // Mandatory Criteria
  {
    id: 'local-building-regulations',
    name: 'Local Building Regulations',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'Approved Plan from local municipal authority.',
    documents: 'Approved Plans',
    points: 0,
  },
  {
    id: 'waste-segregation',
    name: 'Waste Segregation - Dry & Wet',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'Provide 2 separate bins to collect dry and wet waste.',
    documents: 'Photographs of 2 separate bins.',
    points: 0,
  },
  {
    id: 'rainwater-harvesting-500l',
    name: 'Rainwater Harvesting 500 Liters',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'System to capture at least 500 litres from site runoff.',
    documents: 'Photograph of rainwater harvesting pits.',
    points: 0,
  },
  // Credit Criteria
  {
    id: 'passive-architecture-features',
    name: 'Passive Architecture Features',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide any two features mentioned below. For each feature two points (max 4 points): 1. Courtyard 2. Vernacular materials 3. Local Vernacular Elements 4. Any other passive cooling/Heating system 5. Skylights',
    documents: 'Concept description and photographs.',
    points: { New: 4, Existing: 2 },
    options: {
      New: [
        { label: 'One Feature', points: 2 },
        { label: 'Two Features', points: 4 },
      ],
      Existing: [
        { label: 'One Feature', points: 1 },
        { label: 'Two Features', points: 2 },
      ]
    }
  },
  {
    id: 'top-soil-preservation',
    name: 'Top soil Preservation',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Preserve top 150-200 mm of soil during excavation.',
    documents: 'Photographs of top soil preservation.',
    points: 1,
  },
  {
    id: 'passive-architecture-setbacks',
    name: 'Passive Architecture (Setbacks)',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide minimum of 3 ft setback or as per local norms whichever is higher on 2 sides (1 point) More than 2 sides (2 points)',
    documents: 'Photographs of setback areas.',
    points: 2,
    options: [
        { label: '2 sides', points: 1 },
        { label: 'More than 2 sides', points: 2 },
    ]
  },
  {
    id: 'basic-amenities',
    name: 'Basic Amenities',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Access to at least five basic amenities within a 1 km walk.',
    documents: 'Google map showing the distance to amenities.',
    points: 2,
  },
  {
    id: 'vegetation-natural-topography',
    name: 'Vegetation and Natural Topography',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide the vegetation either on Ground/ built - up structures as follows: 30 sq.ft - 1 Point, 50 sq.ft - 2 Points, 75 sq.ft - 3 Points, 100 sq.ft - 4 Points. Note: 1. For the Terrace Landscaping only permenant structures are considered. 2. Potted Plants are not considered. 3. 125sq.ft and above qualifies for exemplary/Innovation',
    documents: 'Photographs of landscape; area details.',
    points: 4,
    options: [
        { label: '30 sq.ft', points: 1 },
        { label: '50 sq.ft', points: 2 },
        { label: '75 sq.ft', points: 3 },
        { label: '100 sq.ft', points: 4 },
    ]
  },
  {
    id: 'vegetables-fruits',
    name: 'Vegetables / Fruits - 2 varieties',
    applicability: { New: false, Existing: true },
    type: 'Credit',
    requirements: 'Grow a minimum of two vegetable/fruit species.',
    documents: 'Photographs of the plants.',
    points: 1,
  },
  {
    id: 'medicinal-plants',
    name: 'Medicinal Plants- 2 varieties',
    applicability: { New: false, Existing: true },
    type: 'Credit',
    requirements: 'Grow a minimum of two medicinal species.',
    documents: 'Photographs of the plants.',
    points: 1,
  },
  {
    id: 'indoor-plants',
    name: 'Indoor Plants - 5 Plants (Minimum)',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Grow a minimum of 5 indoor plants.',
    documents: 'Photographs and a list of the plants.',
    points: 1,
  },
  {
    id: 'vehicle-shading',
    name: 'Vehicle shading',
    applicability: { New: false, Existing: true },
    type: 'Credit',
    requirements: 'Provide shade for vehicles via tree shade or covered parking.',
    documents: 'Photographs of the vehicle shading.',
    points: 1,
  },
  {
    id: 'bicycle-commuting',
    name: 'Bicycle for commuting',
    applicability: { New: false, Existing: true },
    type: 'Credit',
    requirements: 'Use at least one bicycle and provide dedicated parking.',
    documents: 'Photographs of bicycle in its parking space.',
    points: 1,
  },
  {
    id: 'e-vehicle',
    name: 'E-Vehicle/Renewable fuel vehicle',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use at least one E-vehicle, CNG, LPG, or other renewable fuel vehicle.',
    documents: 'Photographs and registration certificate.',
    points: 1,
  },
  {
    id: 'best-practices-construction',
    name: 'Best Practices during Construction',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Implement measures during construction (Barrication, Dust Suppression, etc.). Any 2 measures - 1 Point. Any 4 measures - 2 Points.',
    documents: 'Photographs of each measure.',
    points: 2,
    options: [
        { label: 'Any 2 measures', points: 1 },
        { label: 'Any 4 measures', points: 2 },
    ]
  },
  {
    id: 'white-finish',
    name: 'White finish',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use materials like china mosaic or light-colored paint for the roof.',
    documents: 'Photograph of the roof area finish.',
    points: 2,
  },
  {
    id: 'enhanced-rainwater-harvesting',
    name: 'Enhanced Rainwater Harvesting and Reuse',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Rainwater harvesting system to capture at least 750 Litres (2 points) & Reuse provision for harvested water (2 points). Note: For an existing well or borewell the project shall be awarded 4 points.',
    documents: 'Photograph of pits and reuse application.',
    points: 4,
    selectionType: 'multiple',
    options: [
        { label: 'Harvesting (750L)', points: 2 },
        { label: 'Reuse provision', points: 2 },
        { label: 'Existing Well / Borewell', points: 4 },
    ]
  },
  {
    id: 'water-saving-fixtures',
    name: 'Water Saving Fixtures',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide efficient water fixtures: Dual flush cistern (3 pts), Tap with aerators (2 pts), Showers with aerators (2 pts), Health faucet with aerators (1 pt)',
    documents: 'Photographs of fixtures.',
    points: 8,
    selectionType: 'multiple',
    options: [
        { label: 'Dual flush cistern', points: 3 },
        { label: 'Tap with aerators', points: 2 },
        { label: 'Showers with aerators', points: 2 },
        { label: 'Health faucet with aerators', points: 1 },
    ]
  },
  {
    id: 'water-metering-controllers',
    name: 'Water Metering, Water Level Controllers',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide Water metering (1 Point) and Automatic water level controllers for Overhead tank (1 Point)',
    documents: 'Photographs of the meter and controllers.',
    points: 2,
    selectionType: 'multiple',
    options: [
      { label: 'Water Metering', points: 1 },
      { label: 'Automatic water level controllers', points: 1 }
    ]
  },
  {
    id: 'efficient-envelope',
    name: 'Efficient Envelope',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Use efficient Wall (3 pts) and Roof (2 pts) assemblies.',
    documents: 'Construction photos and roof details.',
    points: 5,
    selectionType: 'multiple',
    options: [
        { label: 'Wall Assembly', points: 3 },
        { label: 'Roof Assembly', points: 2 },
    ]
  },
  {
    id: 'energy-efficient-appliances',
    name: 'Energy Efficient Appliances',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Procure 100% BEE / Energy Certified appliances.',
    documents: 'Photographs of appliances with star ratings.',
    points: { New: 4, Existing: 10 },
    selectionType: 'multiple',
    options: {
      New: [
        { label: 'LED lights', points: 1 },
        { label: '3 Star Energy efficient fans', points: 2 },
        { label: 'Inverter based Refrigerator', points: 1 },
      ],
      Existing: [
        { label: 'LED lights', points: 2 },
        { label: '3 Star Energy efficient fans', points: 3 },
        { label: 'Inverter based Refrigerator', points: 1 },
        { label: '3 Star Inverter Air conditioner', points: 1 },
        { label: '5 Star Inverter Air conditioner', points: 2 },
        { label: 'Any other energy efficient appliances', points: 1 },
      ]
    }
  },
  {
    id: 'sun-shades',
    name: 'Sun shades/ Chajjas',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'All exterior openings must have sun shades of a minimum of 400 mm.',
    documents: 'Photographs of chajjas/sunshades.',
    points: 1,
  },
  {
    id: 'alternate-hot-water',
    name: 'Alternate Hot Water system',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide Solar/LPG/CNG hot water system for 100% of occupants.',
    documents: 'Photographs and technical cutsheets.',
    points: 1,
  },
  {
    id: 'renewable-energy',
    name: 'Renewable Energy',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Install an on-site renewable solar energy system. 0.5 kW (1 pt), 1.5 kW (3 pts), 2.5 kW (5 pts).',
    documents: 'Purchase invoice and photos of panels.',
    points: 5,
    options: [
        { label: '0.5 kW', points: 1 },
        { label: '1.5 kW', points: 3 },
        { label: '2.5 kW', points: 5 },
    ]
  },
  {
    id: 'ev-charging',
    name: 'Electric vehicle charging',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide an electrical charging socket (min 16A) near parking.',
    documents: 'Photographs of the charging socket.',
    points: 1,
  },
  {
    id: 'kitchen-waste-composting',
    name: 'Kitchen waste composting',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide a khamba/compost pit and utilize the manure.',
    documents: 'Photographs of the compost pit.',
    points: 1,
  },
  {
    id: 'green-procurement',
    name: 'Green Procurement - Ecolabelled',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use Green certified materials (1 pt each, max 7 for new, max 2 for existing).',
    documents: 'Photos, cutsheets, and invoices.',
    points: { New: 7, Existing: 2 },
  },
  {
    id: 'local-materials',
    name: 'Local Materials',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Procure materials from manufacturers within 500 KM range. 30% of total cost (1 pt), 40% (2 pts), 50% (3 pts).',
    documents: 'Costing sheet and Google map.',
    points: 3,
     options: [
        { label: '30% of total cost', points: 1 },
        { label: '40% of total cost', points: 2 },
        { label: '50% of total cost', points: 3 },
    ]
  },
  {
    id: 'daylighting',
    name: 'Daylighting',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure 110 Lux daylight in 25% (1 pt) up to 95% (4 pts) of occupied areas.',
    documents: 'Floor plans, photos, and calculation template.',
    points: 4,
    options: [
        { label: '25% of areas', points: 1 },
        { label: '50% of areas', points: 2 },
        { label: '75% of areas', points: 3 },
        { label: '95% of areas', points: 4 },
    ]
  },
  {
    id: 'ventilation',
    name: 'Ventilation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide openable windows that are 5% (1 pt) up to 10% (3 pts) of the carpet area.',
    documents: 'Floor plans, photos, and calculation template.',
    points: 3,
    options: [
        { label: '5% of carpet area', points: 1 },
        { label: '7.5% of carpet area', points: 2 },
        { label: '10% of carpet area', points: 3 },
    ]
  },
  {
    id: 'exhaust-system',
    name: 'Exhaust System',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide exhaust systems in kitchen and bathrooms: Opening (1 pt) and Fan (1 pt).',
    documents: 'Photographs of openings and fans.',
    points: 2,
    selectionType: 'multiple',
    options: [
      { label: 'Opening provision', points: 1 },
      { label: 'Exhaust Fan', points: 1 },
    ]
  },
  {
    id: 'cross-ventilation',
    name: 'Cross Ventilation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure two openings in each space. Living room/Kitchen (1 point), Each Room (1 Point, Max 2)',
    documents: 'Floor plans and photographs of openings.',
    points: 3,
    selectionType: 'multiple',
    options: [
      { label: 'Living room/Kitchen', points: 1 },
      { label: 'Room 1', points: 1 },
      { label: 'Room 2', points: 1 },
    ]
  },
  {
    id: 'exterior-views',
    name: 'Exterior Views',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure a direct line of sight to the outside from each space. Living room/Kitchen (1 point), Each Room (1 Point, Max 2)',
    documents: 'Photographs of exterior views.',
    points: 3,
    selectionType: 'multiple',
    options: [
      { label: 'Living room/Kitchen', points: 1 },
      { label: 'Room 1', points: 1 },
      { label: 'Room 2', points: 1 },
    ]
  },
  {
    id: 'house-automation',
    name: 'House Automation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Install automation devices (1 pt each, max 3 for new, max 2 for existing).',
    documents: 'Technical cutsheets and photographs.',
    points: { New: 3, Existing: 2 },
    selectionType: 'multiple',
    options: [
      { label: 'Lighting Controls', points: 1 },
      { label: 'CCTV', points: 1 },
      { label: 'Solar meter', points: 1 },
      { label: 'Sensors', points: 1 },
    ]
  },
  {
    id: 'green-housekeeping-chemicals',
    name: 'Green House Keeping Chemicals',
    applicability: { New: false, Existing: true },
    type: 'Credit',
    requirements: 'Procure green certified/organic housekeeping chemicals.',
    documents: 'Photographs and purchase invoices.',
    points: 1,
  },
  {
    id: 'innovation-exemplary',
    name: 'Innovation & Exemplary',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Achieve innovative and exemplary performance.',
    documents: 'Supporting proof documents.',
    points: { New: 5, Existing: 3 },
  },
  {
    id: 'igbc-ap',
    name: 'IGBC Accredited Professional / Associate',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Involve an IGBC Accredited Professional/AP Associate.',
    documents: 'IGBC AP Certificate.',
    points: 1,
  },
];


export const certificationLevels: CertificationLevel[] = [
  { level: 'Certified', minScore: { New: 40, Existing: 35 }, color: 'text-blue-500' },
  { level: 'Silver', minScore: { New: 50, Existing: 45 }, color: 'text-gray-500' },
  { level: 'Gold', minScore: { New: 65, Existing: 60 }, color: 'text-yellow-500' },
];
