import type { Criterion, CertificationLevel } from './types';

export const criteria: Criterion[] = [
  // Mandatory Criteria
  {
    id: 'local-building-regulations',
    name: 'Local Building Regulations',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'Approved Plan from local municipal authority.',
    documents: 'Approved Plans',
    points: 0,
  },
  {
    id: 'waste-segregation',
    name: 'Waste Segregation - Dry & Wet',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'Provide 2 separate bins to collect dry waste (paper, plastic, metals, glass, etc.,) and wet waste (organic).',
    documents: 'Photographs of 2 separate bins',
    points: 0,
  },
  {
    id: 'rainwater-harvesting-500l',
    name: 'Rainwater Harvesting 500 Liters',
    applicability: { New: true, Existing: true },
    type: 'Mandatory',
    requirements: 'Rainwater harvesting system to capture at least 500 litres from the entire site area runoff. Or Project can have rainwater harvesting pit to capture run-off from roof.',
    documents: 'Photograph of rainwater harvesting pits',
    points: 0,
  },
  // Credit Criteria
  {
    id: 'passive-architecture',
    name: 'Passive Architecture',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide any two features mentioned below. For each feature two points (max 4 points): 1. Courtyard 2. Vernacular materials 3. Local Vernacular Elements 4. Any other passive cooling/Heating system 5. Skylights',
    documents: 'Concept description of features, Photographs of the passive architecture measure',
    points: { New: 4, Existing: 2 },
  },
  {
    id: 'top-soil-preservation',
    name: 'Top soil Preservation',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Preserve top 150-200 mm soil during excavation',
    documents: 'Photographs of top soil preservation',
    points: 1,
  },
  /*
  // FULL CRITERIA LIST - UNCOMMENT TO RESTORE
  {
    id: 'setbacks',
    name: 'Setbacks',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide minimum of 3 ft setback or as per local norms whichever is higher on 2 sides (1 point) More than 2 sides (2 points)',
    documents: 'Photographs of setback areas',
    points: 2,
  },
  {
    id: 'basic-amenities',
    name: 'Basic Amenities',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Select a site with access to at least five basic amenities within 1 km walking distance from the building entrance - (2 points)',
    documents: 'Google map showing distance of all the local amenities. (Annexure A)',
    points: 2,
  },
  {
    id: 'vegetation-natural-topography',
    name: 'Vegetation and Natural Topography',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide the vegetation either on mother earth/ built - up structures as follows: 30 sq.ft - 1 Point, 50 sq.ft - 2 Points, 75 sq.ft - 3 Points, 100 sq.ft - 4 Points',
    documents: 'Photographs of Landscape and natural topography. Provide the Total Site Area and Landscape Area.',
    points: 4,
  },
  {
    id: 'vegetables-fruits',
    name: 'Vegetables / Fruits - 2 varieties',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Grow a minimum of two vegetable/Fruit species.',
    documents: 'Photographs of the vegetable plants',
    points: 1,
  },
  {
    id: 'medicinal-plants',
    name: 'Medicinal Plants- 2 varieties',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Grow a minimum of two medicinal species',
    documents: 'Photographs of the Medicinal plants',
    points: 1,
  },
  {
    id: 'indoor-plants',
    name: 'Indoor Plants - 5 Plants (Minimum)',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Grow Indoor Plants',
    documents: 'Photographs of the indoor plants. List of indoor plants.',
    points: 1,
  },
  {
    id: 'vehicle-shading',
    name: 'Vehicle shading',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Provide shade for vehicles using either by tree shade or covered parking space.',
    documents: 'Photographs of the vehicles shading',
    points: 1,
  },
  {
    id: 'bicycle-commuting',
    name: 'Bicycle for commuting',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Use at least one bicycle for commuting purpose and provide dedicated parking space.',
    documents: 'Photographs of the bicycle parking in the dedicated parking space',
    points: 1,
  },
  {
    id: 'e-vehicle',
    name: 'E Vehicle/Renewable fuel based vehicle',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use at least one of the following vehicle type-1 point E vehicle CNG based vehicle LPG based vehicle Any other renewable fuel based vehicle',
    documents: 'Photographs of the vehicle, Registration certificate of the vehicle',
    points: 1,
  },
  {
    id: 'best-practices-construction',
    name: 'Best Practices during Contruction',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Implement any 2 measures (1 Point) or any 4 measures (2 Points) from the list: Barrication, Dust Suppression, Material Stacking, Drinking Water and First-Aid, Designated waste material storage space, Soil cover with tarpaulin, Toilet and rest areas for workers',
    documents: 'Photographs of the each measure implemented.',
    points: 2,
  },
  {
    id: 'white-finish',
    name: 'White finish',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use materials with china mosaic/light colored paint/reflective coating/terrace landscaping',
    documents: 'Photograph of roof area with china mosaic/light colored paint/reflective coating/terrace landscaping.',
    points: 2,
  },
  {
    id: 'enhanced-rainwater-harvesting',
    name: 'Enhanced Rainwater Harvesting and Reuse',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Rainwater harvesting system to capture at least 750 Litres (2 points) & Reuse provision for harvested water (2 points)',
    documents: 'Photograph of rainwater harvesting pits, Reuse application',
    points: 4,
  },
  {
    id: 'water-saving-fixtures',
    name: 'Water Saving Fixtures',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide efficient water fixtures: Dual flush cistern (3 pts), Tap with aerators (2 pts), Showers with aerators (2 pts), Health faucet with aerators (1 pt)',
    documents: 'Photographs of taps, health faucet, showers with aerators, and dual flush',
    points: 8,
  },
  {
    id: 'water-metering-controllers',
    name: 'Water Metering, Water Level Controllers',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide Water metering (1 Point) and Automatic water level controllers for Overhead tank (1 Point)',
    documents: 'Photographs of water level controllers, Photograph of water meter',
    points: 2,
  },
  {
    id: 'efficient-envelope',
    name: 'Efficient Envelope',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Implement the energy efficiency measures listed.',
    documents: 'Construction photographs of blocks, Photographs and details of roof assembly',
    points: 5,
  },
  {
    id: 'energy-efficient-appliances',
    name: 'Energy Efficient Appliances',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Procure 100% BEE / Energy Certified for each home appliances listed.',
    documents: 'Photographs of installed energy efficient appliances with star ratings',
    points: { New: 4, Existing: 10 },
  },
  {
    id: 'sun-shades',
    name: 'Sun shades/ Chajjas',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'All exterior openings (fenestration) shall have sun shades/ chajjas of minimum 400 MM.',
    documents: 'Photographs of chajjas/sunshades',
    points: 1,
  },
  {
    id: 'alternate-hot-water',
    name: 'Alternate Hot Water system',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide alternate (Solar/LPG/CNG) hot water system for 100% of occupants (20 Litres/day/person).',
    documents: 'Photographs and technical cutsheets of installed solar hot water system',
    points: 1,
  },
  {
    id: 'renewable-energy',
    name: 'Renewable Energy',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Install on-site renewable solar energy system. 0.5 kW, 1.5 kW, 2.5 kW',
    documents: 'Purchase invoice of solar panels, Photographs of installed solar panels',
    points: 5,
  },
  {
    id: 'ev-charging',
    name: 'Electric vehicle charging',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide electrical charging socket (Min 16A) near the vehicular parking area.',
    documents: 'Photographs of the each electrical charging socket provided',
    points: 1,
  },
  {
    id: 'kitchen-waste-composting',
    name: 'Kitchen waste composting',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide khamba/compost pit for each home. The generated manure shall be utilised as appropriate.',
    documents: 'Photographs of khamba/compost pit',
    points: 1,
  },
  {
    id: 'green-procurement',
    name: 'Green Procurement - Ecolabelled',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Use of Green certified/GreenPro Construction Materials (1 point for each; maximum 5 points for New, 2 for Existing).',
    documents: 'Photographs, Technical cutsheets, and Purchase Invoices of the Green materials',
    points: { New: 5, Existing: 2 },
  },
  {
    id: 'local-materials',
    name: 'Local Materials',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Procure the materials from manufacturers within 500 KM range as listed below.',
    documents: 'Costing sheet of the materials (Annexure 3), Google map showing distance of the manufacturers',
    points: 3,
  },
  {
    id: 'daylighting',
    name: 'Daylighting',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure a minimum daylighting of 110 Lux. 25%, 50%, 75%, 95%',
    documents: 'Floor plans, door/window schedules, elevations, photographs, Daylighting calculation template(Annexure1)',
    points: 4,
  },
  {
    id: 'ventilation',
    name: 'Ventilation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide openable windows to the exterior. 5%, 7.5%, 10% of total carpet area.',
    documents: 'Floor plans, door/window schedules, elevations, photographs, Ventilation calculation template(Annexure2)',
    points: 3,
  },
  {
    id: 'exhaust-system',
    name: 'Exhaust System',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Provide exhaust systems in kitchen and bathrooms: Opening provision (1 point), Exhaust Fan (1 point)',
    documents: 'Photograph of opening and exhaust system in kitchen and bathroom',
    points: 2,
  },
  {
    id: 'cross-ventilation',
    name: 'Cross Ventilation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure two openings (window/ventilator) in each space. Living room/Kitchen (1 point), Each Room (1 Point, Max 2)',
    documents: 'Floor plans highlighting the openings, Photograph of window/door openings',
    points: 3,
  },
  {
    id: 'exterior-views',
    name: 'Exterior Views',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Ensure direct line of sight to vision glazing. Living room/Kitchen (1 point), Each Room (1 Point, Max 2)',
    documents: 'Photographs of the exterior views from each living space.',
    points: 3,
  },
  {
    id: 'home-automation',
    name: 'House Automation',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Install home automation devices. One point for each item (Max 3 for New, 2 for Existing).',
    documents: 'Technical cutsheets and photographs of the installed Appliances',
    points: { New: 3, Existing: 2 },
  },
  {
    id: 'green-housekeeping-chemicals',
    name: 'Green House Keeping Chemicals',
    applicability: { New: true, Existing: false },
    type: 'Credit',
    requirements: 'Procure the green certified/organic house keeping chemicals.',
    documents: 'Photographs and Purchase invoices of housekeeping chemicals',
    points: 1,
  },
  {
    id: 'innovation-exemplary',
    name: 'Innovation & Exemplary',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Innovative and exemplary performance in the green building categories.',
    documents: 'Supporting proof documents of each innovation and exemplary credits.',
    points: { New: 5, Existing: 3 },
  },
  {
    id: 'igbc-ap',
    name: 'IGBC Accredited Professional / Associate',
    applicability: { New: true, Existing: true },
    type: 'Credit',
    requirements: 'Support and Encourage the involvement of IGBC Accredited Professional /AP Associate in the project.',
    documents: 'IGBC Accredited Professional Certificate.',
    points: 1,
  },
  */
];


export const certificationLevels: CertificationLevel[] = [
  { level: 'Certified', minScore: { New: 40, Existing: 35 }, color: 'text-blue-500' },
  { level: 'Silver', minScore: { New: 50, Existing: 45 }, color: 'text-gray-500' },
  { level: 'Gold', minScore: { New: 65, Existing: 60 }, color: 'text-yellow-500' },
];
